### ISSUE TITLE
Images in Button component lose their sizing ratio

### ISSUE THREAD

**Issue by kkashi01** [Kodular/Kodular-Creator-Issue-Tracker#12]
From community: https://community.kodular.io/t/images-retain-original-size/18500

Buttons that include Image, seems to loose their sizing ratio when images is smaller than the button’s default height and width which is h48xw88

Dev Note. MIT: 3ed2f95a2c1c5e30454b7e4bd5c0d675de39b60d

**Comment by conorshipp** [comment]
Fixed in Kodular Eagle 1.4C.0
