### ISSUE TITLE
In app billing subscription block not working

### ISSUE THREAD

**Issue by kkashi01** [Kodular/Kodular-Creator-Issue-Tracker#15]
From community:
https://community.kodular.io/t/in-app-billing-wont-show-subscription/50538/5

Subscription block not working

**Comment by programmer882** [comment]
Could you help me brother to show example of simple block subscription for premium feature that will remove ads

**Comment by ontstudios** [comment]
> Could you help me brother to show example of simple block subscription for premium feature that will remove ads

this is not a place to ask for help.

**Comment by pavi2410** [comment]
Fixed
