### ISSUE TITLE
DrawPoly - Update Canvas.DrawPolygon to clear canvas

### ISSUE THREAD

**Issue by kkashi01** [Kodular/Kodular-Creator-Issue-Tracker#2]
Community request: Canvas.DrawPolygon method clears the canvas every time is executed. Can that be changed to work as the other drawing methods work?

**Comment by conorshipp** [comment]
The next release will have a parameter to choose whether or not to clear the canvas when drawing a polygon.
![](https://user-images.githubusercontent.com/25845449/71833534-05025f00-30a5-11ea-9914-ecb6553f6751.png)

**Comment by conorshipp** [comment]
Fixed in Kodular Eagle 1.4C.0
