### ISSUE TITLE
Problem is Exported aia And Screens are corrupted.

### ISSUE THREAD

**Issue by imrantariq786** [Kodular/Kodular-Creator-Issue-Tracker#24]
**Describe the bug**
Exported aia and ais are not working, if i am exporting any aia it misses scr folder from aia and didnt imported and if i export any screen it always exported screen1 instead of selected screen.

**Additional context**
because this issue i have posted to Community and Slack also, and i think you can check a file given by Boban [https://community.kodular.io/t/i-canot-enter-my-aia-after-export-it/57351/27?u=imrantariq](url) at community for test, that exported aia missed screens folder and cant imported to Kodular.

**Comment by conorshipp** [comment]
Fixed in Kodular Eagle 1.4C.2
