### ISSUE TITLE
Scratch Blocks

### ISSUE THREAD

**Issue by m93a** [Kodular/Kodular-Creator-Issue-Tracker#28]
**Describe the desired feature**
[Scratch](https://scratch.mit.edu/) – the famous programming platform for kids – developed its own version of Google Blockly, called [Scratch Blocks](https://github.com/llk/scratch-blocks). While it can't do everything that Blockly can, it is graphically superior and simplifies some of the concepts significantly. Kodular would benefit from giving up MIT AI's blocks and moving to Scratch Blocks.

**Comparions of Kodular and Scratch code**

![when this sprite clicked delete all of list, add thing to list](https://user-images.githubusercontent.com/1671665/81726595-ed3e4b80-9487-11ea-8269-075e6c667cf9.png)

![when Button1.Click do set global list to create empty list, add items to list list get global list item “thing”](https://user-images.githubusercontent.com/1671665/81726501-c3852480-9487-11ea-91db-be152810eabe.png)

----

![repeat until a = 50 change a by 1](https://user-images.githubusercontent.com/1671665/81726159-3772fd00-9487-11ea-8b33-282153e65ccb.png)

![while test get global a < 50 do set global a to get global a + 1](https://user-images.githubusercontent.com/1671665/81726074-10b4c680-9487-11ea-9e4d-cfc328a28b56.png)

----

![insert item 1 of list at 2 of list](https://user-images.githubusercontent.com/1671665/81726899-69d12a00-9488-11ea-9ab7-eb12bf7b364d.png)

![insert list item list get global list index 2 item select list item list get global list item 1](https://user-images.githubusercontent.com/1671665/81726824-4a3a0180-9488-11ea-90e2-3c77173505ef.png)

----

**Pros of Scratch Blocks**
 * better visuals
 * the code reads like a sentence
 * they are more linear and easier to follow
 * numeric and string fields have a textbox (⇒ much faster workflow)
 * they don't blindly follow the structure of typed code, making certain constructs far more natural for the “block”-ed code
 * dragging a block back to the left panel deletes it (⇒ faster workflow)
 * they share the Blockly API (⇒ almost a drop-in replacement)

**Cons of Scratch Blocks**
 * they lack several advanced blocks of MIT AI, eg. dictionaries
 * the lack of „puzzle connections“ could make some complicated code look like spaghetti
 * they don't have [mutators](https://developers.google.com/blockly/guides/create-custom-blocks/extensions) which is the only part where the workflow is worse than in Blockly

**Comment by Kanishka-Developer** [comment]
The cons honestly outweigh the pros. Scratch is designed primarily for kids, while Kodular is an advanced platform for making apps quickly without _typing_ code. Blockly is a middle ground between Scratch and other programming languages, and I feel that is the sweet spot. Simpler and you lose power, more complicated, and non-programmers will be unable to use the platform.

Last but not the least, "looks" are subjective. Personally, Kodular blocks > App Inventor blocks > Scratch.

Scratch also takes away the loose typing in many cases, which is an incredibly powerful tool if you know how to juggle data types.

Just my two cents.

**Comment by m93a** [comment]
From your comment I have the impression that you don't know Scratch Blocks very well. Yes, Scratch itself is for kids, but not Scratch Blocks. I struggle to think of a single feature of Scratch Blocks that is “better for kids and worse for adults” than Google Blockly (apart from the mutators I mentioned, but those could be ported back relatively easily).

**“The cons honestly outweigh the pros.”**
I think that all of the cons that I mentioned can be fixed with ~100 lines of code. Could you please be more specific about what you miss in Scratch Blocks that can't be easily fixed and would be a deal-breaker for Kodular?

**“Blockly is a middle ground between Scratch and other programming languages.”**
To be honest, I don't think it is. Blockly is a project that brought programming to masses without the need to type code. Scratch Blocks is *that project, refined*. In the beginning of Scratch, Scratch Blocks *were* Google Blockly but while the design of Blockly was freezed, Scratch was tweaked re-thought for a few more years. Yes, it became simpler, but in a good way. It's still as capable as Blockly.

You're right that the looks are subjective, but I would argue that the workflow of Scratch Blocks is **objectively superior** to that of Blockly. I recommend that you give Scratch Blocks another chance, and if you're still not convinced, I can put together several showcases (screencaps, demos) to prove my point.

**“Scratch also takes away the loose typing in many cases”**
If I understand you correctly, you're referring to the “two types of holes” in Scratch Blocks, compared to “one type of puzzle connection” in Blockly (see image below). Well, using this is completely optional, you can make all blocks out of the “(round) hole”. Or you could use the “(round) hole” for primitive types and save the “&lt;angled> hole” for objects. Having more options isn't a bad thing, is it?

![image](https://user-images.githubusercontent.com/1671665/82226408-c28c4100-9926-11ea-82c0-7f11a3c56ab5.png)
![image](https://user-images.githubusercontent.com/1671665/82226445-cb7d1280-9926-11ea-8abf-69cf90e48ee3.png)


**I'm not *forcing* you in any way to migrate to Scratch Blocks.** In the end, I don't know whether Scratch Blocks are actually better for Kodular, but I still think **you don't know what you're missing.**  There are awesome features in Scratch Blocks that could at the very least inspire the next development of Kodular.
