### ISSUE TITLE
Add API Level 29

### ISSUE THREAD

**Issue by Kanishka-Developer** [Kodular/Kodular-Creator-Issue-Tracker#5]
Now that Android 10 has had its stable release, we should have the option to set **MinAPI** to **29**. Also, maybe TargetAPI should also move to 29? Not quite sure about the implications of the latter.

**Comment by yanquisalexander** [comment]
https://community.kodular.io/t/kodular-eagle/34126/13?u=alexitoo_uy

This Issue should be closed...
