### ISSUE TITLE
Broken links in Creator

### ISSUE THREAD

**Issue by yanquisalexander** [Kodular/Kodular-Creator-Issue-Tracker#8]
**Describe the bug**

Help links in Creator are "broken", they do not point to one direction, but to "text"

**To Reproduce**
1. Go to the Components Palette
2. Click on 'Info Button'
3. Click or hover on "Learn More at docs.kodular.io"

**Screenshots**

![Broken Link](https://user-images.githubusercontent.com/53713818/72388247-3a8df480-3704-11ea-9fe8-764f883f05ba.PNG)

**Comment by barreeeiroo** [comment]
Related: https://community.appinventor.mit.edu/t/bug-in-class-componentprocessor/2718?u=diego

**Comment by yanquisalexander** [comment]
Issue closed: The problem has already been solved

https://community.kodular.io/t/kodular-eagle/34126/8
