### ISSUE TITLE
Package_Utilities / permission requested

### ISSUE THREAD

**Issue by kkashi01** [Kodular/Kodular-Creator-Issue-Tracker#9]
https://community.kodular.io/t/package-utilities-permission-requested/49260

EXTERNAL_STORAGE needed only for **GetPackageIcon** block

**Comment by pavi2410** [comment]
https://github.com/Kodular/Kodular-Creator/issues/893

**Comment by SivagiriVisakan** [comment]
Fixed in version 1.4C.0
